[package]
name = "clarirs_num"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
num-bigint = "0.4.6"
serde = "1.0.209"
smallvec = "1.13.2"
thiserror = "1.0.63"

[lints]
workspace = true
