use crate::prelude::*;

pub trait ToOpString {
    fn to_opstring(&self) -> String;
}

impl ToOpString for AstRef<'static> {
    fn to_opstring(&self) -> String {
        match self.op() {
            // Bool ops
            Op::BoolS(..) => "BoolS".to_string(),
            Op::BoolV(..) => "BoolV".to_string(),
            Op::Not(..) => "Not".to_string(),
            Op::And(..) => "And".to_string(),
            Op::Or(..) => "Or".to_string(),
            Op::Xor(..) => "Xor".to_string(),
            Op::BoolEq(..) => "__eq__".to_string(),
            Op::BoolNeq(..) => "__ne__".to_string(),
            Op::Eq(..) => "__eq__".to_string(),
            Op::Neq(..) => "__ne__".to_string(),
            Op::ULT(..) => "ULT".to_string(),
            Op::ULE(..) => "ULE".to_string(),
            Op::UGT(..) => "UGT".to_string(),
            Op::UGE(..) => "UGE".to_string(),
            Op::SLT(..) => "SLT".to_string(),
            Op::SLE(..) => "SLE".to_string(),
            Op::SGT(..) => "SGT".to_string(),
            Op::SGE(..) => "SGE".to_string(),
            Op::FpEq(..) => "fpEQ".to_string(),
            Op::FpNeq(..) => "fpNEQ".to_string(),
            Op::FpLt(..) => "fpLT".to_string(),
            Op::FpLeq(..) => "fpLEQ".to_string(),
            Op::FpGt(..) => "fpGT".to_string(),
            Op::FpGeq(..) => "fpGEQ".to_string(),
            Op::FpIsNan(..) => "fpIsNan".to_string(),
            Op::FpIsInf(..) => "fpIsInf".to_string(),
            Op::StrContains(..) => "StrContains".to_string(),
            Op::StrPrefixOf(..) => "StrPrefixOf".to_string(),
            Op::StrSuffixOf(..) => "StrSuffixOf".to_string(),
            Op::StrIsDigit(..) => "StrIsDigit".to_string(),
            Op::StrEq(..) => "__eq__".to_string(),
            Op::StrNeq(..) => "__ne__".to_string(),
            Op::ITE(..) => "If".to_string(),

            // BitVec ops
            Op::BVS(..) => "BVS".to_string(),
            Op::BVV(..) => "BVV".to_string(),
            Op::BVNot(..) => "__neg__".to_string(),
            Op::BVAnd(..) => "__and__".to_string(),
            Op::BVOr(..) => "__or__".to_string(),
            Op::BVXor(..) => "__xor__".to_string(),
            Op::Neg(..) => "__neg__".to_string(),
            Op::Add(..) => "__add__".to_string(),
            Op::Sub(..) => "__sub__".to_string(),
            Op::Mul(..) => "__mul__".to_string(),
            Op::UDiv(..) => "__floordiv__".to_string(),
            Op::SDiv(..) => "SDiv".to_string(),
            Op::URem(..) => "__mod__".to_string(),
            Op::SRem(..) => "SMod".to_string(),
            Op::ShL(..) => "__lshift__".to_string(),
            Op::LShR(..) => "LShR".to_string(),
            Op::AShR(..) => "__rshift__".to_string(),
            Op::RotateLeft(..) => "RotateLeft".to_string(),
            Op::RotateRight(..) => "RotateRight".to_string(),
            Op::ZeroExt(..) => "ZeroExt".to_string(),
            Op::SignExt(..) => "SignExt".to_string(),
            Op::Extract(..) => "Extract".to_string(),
            Op::Concat(..) => "Concat".to_string(),
            Op::ByteReverse(..) => "Reverse".to_string(),
            Op::FpToIEEEBV(..) => "fpToIEEEBV".to_string(),
            Op::FpToUBV(..) => "fpToUBV".to_string(),
            Op::FpToSBV(..) => "fpToSBV".to_string(),
            Op::StrLen(..) => "StrLen".to_string(),
            Op::StrIndexOf(..) => "StrIndexOf".to_string(),
            Op::StrToBV(..) => "StrToBV".to_string(),
            Op::ITE(..) => "If".to_string(),
            Op::Union(..) => "Union".to_string(),
            Op::Intersection(..) => "Intersection".to_string(),
            Op::Widen(..) => "Widen".to_string(),

            // Float ops
            Op::FPS(..) => "FPS".to_string(),
            Op::FPV(..) => "FPV".to_string(),
            Op::FpNeg(..) => "fpNeg".to_string(),
            Op::FpAbs(..) => "fpAbs".to_string(),
            Op::FpAdd(..) => "fpAdd".to_string(),
            Op::FpSub(..) => "fpSub".to_string(),
            Op::FpMul(..) => "fpMul".to_string(),
            Op::FpDiv(..) => "fpDiv".to_string(),
            Op::FpSqrt(..) => "fpSqrt".to_string(),
            Op::FpToFp(..) => "fpToFp".to_string(),
            Op::FpFP(..) => "fpFP".to_string(),
            Op::BvToFp(..) => "bvToFP".to_string(),
            Op::BvToFpSigned(..) => "fpToFPSigned".to_string(),
            Op::BvToFpUnsigned(..) => "fpToFPUnsigned".to_string(),
            Op::ITE(..) => "If".to_string(),

            // String ops
            Op::StringS(..) => "StringS".to_string(),
            Op::StringV(..) => "StringV".to_string(),
            Op::StrConcat(..) => "StrConcat".to_string(),
            Op::StrSubstr(..) => "StrSubstr".to_string(),
            Op::StrReplace(..) => "StrReplace".to_string(),
            Op::BVToStr(..) => "IntToStr".to_string(),
            Op::ITE(..) => "If".to_string(),
        }
    }
}
